server:
  port: 8080
  servlet:
    context-path: /ordering-system

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.190.161.103:3306/ordering-system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #字段为空的json数据不展示
  jackson:
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates/
    content-type: text/html; charset=UTF-8
    suffix: .ftl
  redis:
    database: 1
    port: 6379
    host: 118.190.161.103
    password: 123456

wechat:
  mpAppId: wxb6ed15da5ef7656c
  mpAppSecret: 135d1e6fd2415709fafacf3031cd46d5

projecturl:
  wechatMpAuthorize: http://dongtian.viphk.ngrok.org
  wechatOpenAuthorize: http://dongtian.viphk.ngrok.org
  orderingSystem: http://dongtian.viphk.ngrok.org
